### ISSUE TITLE
Can't recognize USB devices

### ISSUE THREAD

**Issue by ghost** [Googulator/LumiaUSBC#1]
I used your latest USB driver and imbushuo's latest UEFI, but when I plugged mice,keyboard and udisk through the USB-C adapter without external power source, OS can't recognize my devices.

**Comment by SuperJMN** [comment]
It's a known issue :(

**Comment by PatjedG** [comment]
My lumia 950XL won't charge after installing Windows 10 ARM i tried to update with this driver but didn't work. If in dual boot and boot Windows Mobile then the phone will charge the battery. A also included the driver package before using de WoA tool.

**Comment by SuperJMN** [comment]
@PatjedG this issue isn't because of this driver. Please, check this out: https://www.woaproject.net/viewtopic.php?f=16&t=6

**Comment by PatjedG** [comment]
Thanks I didn't know that, lot of thanks for the quick answer and the work you guys put into it 😊

________________________________
Van: José Manuel Nieto <notifications@github.com>
Verzonden: Sunday, February 3, 2019 9:48:30 PM
Aan: Googulator/LumiaUSBC
CC: PatjedG; Mention
Onderwerp: Re: [Googulator/LumiaUSBC] Can't recognize USB devices (#1)


@PatjedG<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPatjedG&data=02%7C01%7C%7Cecbd3fc3175344b8b02408d68a18f598%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636848237136330381&sdata=ppkhGagfsFoZ7kNtwyKlaaSPa75n3Zpqt8ySayzfq64%3D&reserved=0> this issue isn't because of this driver. Please, check this out: https://www.woaproject.net/viewtopic.php?f=16&t=6<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.woaproject.net%2Fviewtopic.php%3Ff%3D16%26t%3D6&data=02%7C01%7C%7Cecbd3fc3175344b8b02408d68a18f598%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636848237136340387&sdata=iyxUCcuW19EdoK1cTWRtkCBz6fap6MfUSCMaeNxn%2FRk%3D&reserved=0>
